/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conhash;

public class App {
    public String getGreeting() {
        return "Hello, Welcome to Consistent Hashing Project!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
